/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoArtigoRouteImport } from './routes/novo-artigo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaNameRouteImport } from './routes/categoria.$name'
import { Route as ArtigoSlugRouteImport } from './routes/artigo.$slug'

const NovoArtigoRoute = NovoArtigoRouteImport.update({
  id: '/novo-artigo',
  path: '/novo-artigo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaNameRoute = CategoriaNameRouteImport.update({
  id: '/categoria/$name',
  path: '/categoria/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoSlugRoute = ArtigoSlugRouteImport.update({
  id: '/artigo/$slug',
  path: '/artigo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/novo-artigo': typeof NovoArtigoRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$name': typeof CategoriaNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/novo-artigo': typeof NovoArtigoRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$name': typeof CategoriaNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/novo-artigo': typeof NovoArtigoRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$name': typeof CategoriaNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/novo-artigo' | '/artigo/$slug' | '/categoria/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/novo-artigo' | '/artigo/$slug' | '/categoria/$name'
  id: '__root__' | '/' | '/novo-artigo' | '/artigo/$slug' | '/categoria/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovoArtigoRoute: typeof NovoArtigoRoute
  ArtigoSlugRoute: typeof ArtigoSlugRoute
  CategoriaNameRoute: typeof CategoriaNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo-artigo': {
      id: '/novo-artigo'
      path: '/novo-artigo'
      fullPath: '/novo-artigo'
      preLoaderRoute: typeof NovoArtigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$name': {
      id: '/categoria/$name'
      path: '/categoria/$name'
      fullPath: '/categoria/$name'
      preLoaderRoute: typeof CategoriaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo/$slug': {
      id: '/artigo/$slug'
      path: '/artigo/$slug'
      fullPath: '/artigo/$slug'
      preLoaderRoute: typeof ArtigoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovoArtigoRoute: NovoArtigoRoute,
  ArtigoSlugRoute: ArtigoSlugRoute,
  CategoriaNameRoute: CategoriaNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
